### ISSUE TITLE
d3.html throws `document is not defined` in Node.js

### ISSUE THREAD

**Issue by mindrones** [d3/d3-request#10]
This code
```js
// npm install --save d3@next

d3.html('https://foo.org/', function(err, documentFragment) {
  if (err) throw err;
  parseDoc(d3.select(documentFragment))
})

function parseDoc(doc) {
  console.log(doc.selectAll('span'));
}

```
throws
```bash
ReferenceError: document is not defined
```
as indeed in Node.js `document` is not defined in [`src/html.js`](https://github.com/d3/d3-request/blob/14717ea3c040829d19d181f257d9681c41367059/src/html.js)

**Comment by mbostock** [comment]
This is the expected behavior: Node does not provide a document object model by default, so you’d need to specify your own (such as JSDOM) if you want to use this method. I thought that this was documented already, but I can’t seem to find it now. I will update the documentation accordingly.

**Comment by mindrones** [comment]
Ah OK thanks.
I'm Indeed using something like this now:

```js
var jsdom = require('jsdom')
var d3 = fs.readFileSync('./node_modules/d3/d3.js', 'utf-8');
jsdom.env({
    url: 'https://foo.org/',
    src: [d3],
    done: function(err, window) {
        if (err) { throw err }

        var d3 = window.d3;
        console.log(d3.selectAll('span'));
    }
})
```
which is a bit convoluted but works :)

**Comment by mbostock** [comment]
Yeah, using JSDOM directly seems reasonable. You can avoid injecting D3 if you avoid the D3 methods that require a global document. For example, this logs the src attribute of the current Google doodle:

```js
var d3 = require("d3"),
    jsdom = require("jsdom");

jsdom.env("https://google.com", function(error, window) {
  if (error) throw error;
  console.log(d3.select(window.document).select("#hplogo").attr("src"));
});
```

[![120th-anniversary-of-first-modern-olympic-games-6314245085986816 2-5640471028170752-ror](https://cloud.githubusercontent.com/assets/230541/14326535/4a125ab4-fbe3-11e5-8fce-f69171c5fe99.jpg)
](https://www.google.com/logos/doodles/2016/120th-anniversary-of-first-modern-olympic-games-6314245085986816.2-5640471028170752-ror.jpg)

**Comment by mindrones** [comment]
Perfect, using `var doc = d3.select(window.document)` and always selecting from it is fine with me in this case, thanks for the advice!

**Comment by hems** [comment]
@mbostock what if i just want to create the SVG string from a node.js server? can't i use d3 methods without having to provide a global "document" object?

**Comment by martijndormans** [comment]
Any update on the last comment? Having trouble with it.

**Comment by curran** [comment]
JSDOM should work. What have you tried?

**Comment by martijndormans** [comment]
yis i got it working now, something was wrong with the library I am using ontop of d3
