### ISSUE TITLE
import statement not working 

### ISSUE THREAD

**Issue by parliament718** [d3/d3-request#16]
I'm having this issue here http://stackoverflow.com/q/39909200/1267778 where a simple import statement does not work for d3-request.

    import * as d3select from 'd3-selection';
    import * as d3request from 'd3-request';

    var mysvg = d3select.select("#mysvg"); //works
    var request = d3request.xml('assets/emojis/laughing.svg'); //doesnt work

The d3select call gets properly compiled to the exported "select" function. However the resulting code for the second line compiles to something like:

    var d3Request$1 = unwrapExports(d3Request);

    var d3Request$2 = Object.freeze({
        default: d3Request$1,
        __moduleExports: d3Request
    });

And then tries to call ` d3Request$2.xml`, which doesn't exist.

**Comment by mbostock** [comment]
It looks like whatever bundled you are using is not importing the code from the ES2015 source, per the module (and jsnext:main) entry point defined in the package.json. I am not familiar with the bundler you are using, and you didn’t post that part of your code, but that’s where I would look.

**Comment by parliament718** [comment]
I'm trying to load d3 in an Ionic2 app. They have settled for Rollup as the bundler and here is the default script the doesn't the bundling: https://github.com/driftyco/ionic-app-scripts/blob/master/config/rollup.config.js

I'm new to a lot of concepts here, how can I edit the build script to include the correct entry point for d3?
