### ISSUE TITLE
Unable to get xhr.status

### ISSUE THREAD

**Issue by GordonSmith** [d3/d3-request#19]
I don't believe its possible to get the status code within the ```on("error", ...)``` callback?  
Might be nice to have full access to the xhr object?

**Comment by mbostock** [comment]
The error callback is passed the ProgressEvent that describes the error, and you can access the XMLHttpRequest as [*error*.target](https://www.w3.org/TR/dom/#event).

```js
request.on("error", function(error) {
  console.log(error.target.status);
});
```

**Comment by GordonSmith** [comment]
I suspect the issue I was seeing was again with the XMLHTTPRequest polyfil as its status was "0" when it should have been a 401 - again not an issue with d3-request.
