### ISSUE TITLE
FYI Dependency Issue

### ISSUE THREAD

**Issue by GordonSmith** [d3/d3-request#20]
The following issue is preventing d3-request.post to work correctly in node.js:
https://github.com/driverdan/node-XMLHttpRequest/pull/137

**Comment by mbostock** [comment]
If this is a bug in the polyfill I see no reason to also track the bug here, but thank you for letting me know.

**Comment by GordonSmith** [comment]
Yup, just a FYI - unfortunately it looks like that project has stalled...
