### ISSUE TITLE
d3.request is not a function

### ISSUE THREAD

**Issue by ymz1124** [d3/d3-request#22]
I find d3.request in the API document but when I write this code in my project, there raise the error about 'd3.request is not a function'

**Comment by curran** [comment]
Can you please post an example that reproduces the error? Thank you.

**Comment by ymz1124** [comment]
I'm sorry, I have made a mistake. It works now. Thank you for offering such cool tool!

**Comment by curran** [comment]
Great! Feel free to close this issue.

**Comment by dhruvdcoder** [comment]
What was the mistake ? I am getting the same error.

**Comment by ymz1124** [comment]
Sorry, I have forgotten the mistake... I'll write down next time to help others like you.
