### ISSUE TITLE
Expose XHR status on error

### ISSUE THREAD

**Issue by aviddiviner** [d3/d3-request#23]
Hi.

When I get a 404 response, the "error" event that's fired only includes an XHR ProgressEvent (in Chrome), and nothing else. That would be [this code path](https://github.com/d3/d3-request/blob/v1.0.5/src/request.js#L42).

This isn't too helpful, and I was wondering if you could expose the `xhr.status` or more details of the underlying XHR itself. Perhaps either as an extra part of the error payload, or similarly to how you allow the user access to the XHR on the [_request_.**response**(_fn_)](https://github.com/d3/d3-request#request_response) method.

I like that I can do
```js
.response(function(xhr) { /* do something with xhr.responseText */ })
```

So on an error I want to
```js
.errorResponse(function(xhr) { /* check xhr.status or xhr.getAllResponseHeaders() */ })
```
Thanks!
And thanks for the amazing software. You rock!

**Comment by mbostock** [comment]
You can use *error*.target on the ProgressEvent passed to the error handler to get back the underlying XMLHttpRequest instance. For example:

```js
d3.text("/file/not/found", function(error, text) {
  if (error) {
    console.log("fail", error.target.status);
  } else {
    console.log("success", text);
  }
});
```
