### ISSUE TITLE
Version 1.0.6 breaks build because of XmlHtppRequest dependency

### ISSUE THREAD

**Issue by alexweltman** [d3/d3-request#25]
Webpack fails with the error ```Module not found: Error: Cannot resolve module 'child_process'```.
child_process is required in XMLHttpRequest. 

I resolved this by adding XMLHttpRequest to my Webpack externals, but seems like I shouldn't have to do that.  
```
externals:[{
    xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
}]
```

child_process cannot be used in the browser - why is is needed?

**Comment by mbostock** [comment]
Closing as duplicate of #24. It looks like you were depending on unsupported entry points in the package.json; you’ll need to reconfigure your bundler to consume the code intended for browsers rather than for Node, preferably by consuming the ES modules (the `module` field in the package.json).

**Comment by alexweltman** [comment]
thanks!
