### ISSUE TITLE
default port on localhost

### ISSUE THREAD

**Issue by mathisonian** [d3/d3-request#30]
When I'm running a server on localhost on some port, say 3000, and use d3-request to reference a file from the root url, e.g. 

```
const d3 = require('d3-request');
d3.json('/my-data.json', ...)
```

this sends a GET request to `http://localhost/my-data.json`, while I'd expect it to be routed to `http://localhost:3000/my-data.json`. To be clear the javascript and html is loading from `localhost:3000` as well in this case. 

Using [superagent](https://visionmedia.github.io/superagent/) or [this ajax snippet from SO](https://stackoverflow.com/questions/18360935/accessing-json-data-from-a-url/18361648#18361648) I can request `/my-data.json` and it is fetched correctly.

**Comment by mbostock** [comment]
Unable to reproduce. This worked fine for me using `http-server -p 3000`.

https://gist.github.com/mbostock/fd652a3fc1a41243d92e2cee6cbd6711

**Comment by mathisonian** [comment]
I'm able to consistently reproduce this, but only in a commonjs environment. I ran your code locally and it worked as expected, and tested using rollup to build a bundle ([repo here](https://github.com/mathisonian/d3-request-test)) and that also worked as expected. 

However, using commonjs I get the behavior described above, unclear why. To reproduce easily, I've made a repo to help reproduce the problem: https://github.com/mathisonian/d3-request-test-cjs.

**Comment by mbostock** [comment]
It’s because you are consuming the code that is targeted at Node and has an XMLHttpRequest polyfill, rather than code targeted at the browser. You need to use the module entry point if you are using a browser-targeting bundle. (Or, you can rebundle the UMD provided with the release.)

**Comment by mathisonian** [comment]
Got it - thanks @mbostock.

**Comment by mbostock** [comment]
You are very welcome! Sorry for the lost time.

**Comment by naxxateux** [comment]
Thanks @mathisonian and @mbostock. You saved my day.
