### ISSUE TITLE
Unable to use as standalone library per docs

### ISSUE THREAD

**Issue by mvdobrinin** [d3/d3-request#38]
See https://jsfiddle.net/k7neco5x/4/.

> Uncaught TypeError: headers.each is not a function
>     at Object.send (d3-request.v1.js:113)
>     at Object.get (d3-request.v1.js:101)
>     at (index):48

The README mentions the standalone as the following file - https://d3js.org/d3-request.v1.min.js, but I can only get it to work if I add the other dependency files. Should the docs point to a different file as the standalone version?

**Comment by mbostock** [comment]
As described in the README, this library has three dependencies: d3-collection, d3-dispatch, and d3-dsv. The “standalone” here means “apart from the D3 default bundle”, not zero dependencies.

https://github.com/d3/d3-request/tree/master#installing
