### ISSUE TITLE
Failing tests and crashing since 0.2.0

### ISSUE THREAD

**Issue by xaranke** [d3/d3-request#6]
Hi,

I've noticed that the package fails 10/82 tests in versions 0.2.0, 0.2.1 and 0.2.2. 
However, more severely, it also seems to crash the npm republish script. 

I tried to debug it but the error message is very vague. [Here](https://github.com/d3/d3-request/files/49216/npm-debug.log.txt) is the error log I received.

Hope that helps and keep up the good work on v4.0!

**Comment by mbostock** [comment]
Sorry; I had been testing against an old version of [d3-dsv](https://github.com/d3/d3-dsv), which now exposes a `columns` field on the loaded data as of [version 0.1.10](https://github.com/d3/d3-dsv/releases/tag/v0.1.10).
